[blockchain_a]
type = 'anvil'
image = 'f4hrenh9it/foundry'
tag = 'latest'
port = '8500'
chain_id = '31337'
docker_cmd_params = ['--block-time=1']

[blockchain_a.out]
chain_id = '31337'

[[blockchain_a.out.nodes]]
ws_url = 'ws://127.0.0.1:32993/tcp'
http_url = 'http://127.0.0.1:32993/tcp'
docker_internal_ws_url = 'ws://anvil-53668:8500'
docker_internal_http_url = 'http://anvil-53668:8500'

[blockchain_b]
type = 'anvil'
image = 'f4hrenh9it/foundry'
tag = 'latest'
port = '8546'
chain_id = '31338'
docker_cmd_params = ['--block-time=1']

[data_provider]
port = 9111

[data_provider.out]
data_provider_urls = ['http://localhost:8080/mock1', 'http://localhost:8080/mock2']

[don]
[[don.nodes]]
data_provider_url = 'http://localhost:8080/mock1'

[don.nodes.db]
user = 'chainlink'
password = 'thispasswordislongenough'
database = 'chainlink'
port = '5432'

[don.nodes.node]
image = 'public.ecr.aws/chainlink/chainlink'
tag = 'v2.17.0'
port = '6688'
test_config_overrides = "\n\t[[EVM]]\n\tChainID = '31337'\n\tMinIncomingConfirmations = 1\n\tMinContractPayment = '0.0001 link'\n\n\t\n\t[[EVM.Nodes]]\n\tName = 'default'\n\tWsUrl = 'ws://anvil-53668:8500'\n\tHttpUrl = 'http://anvil-53668:8500'\n\t\n\t"
user_config_overrides = "[Log]\nLevel = 'debug'\n"
test_secrets_overrides = ''
user_secrets_overrides = ''

[don.nodes.out]
[don.nodes.out.node]
url = '127.0.0.1:32995'
docker_internal_url = 'http://clnode-cd9e2:6688'

[don.nodes.out.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:32994/chainlink?sslmode=disable'
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@postgresql-6d6d0:5432/chainlink?sslmode=disable'

[[don.nodes]]
data_provider_url = 'http://localhost:8080/mock1'

[don.nodes.db]
user = 'chainlink'
password = 'thispasswordislongenough'
database = 'chainlink'
port = '5432'

[don.nodes.node]
image = 'public.ecr.aws/chainlink/chainlink'
tag = 'v2.17.0'
port = '6688'
test_config_overrides = "\n\t[[EVM]]\n\tChainID = '31337'\n\tMinIncomingConfirmations = 1\n\tMinContractPayment = '0.0001 link'\n\n\t\n\t[[EVM.Nodes]]\n\tName = 'default'\n\tWsUrl = 'ws://anvil-53668:8500'\n\tHttpUrl = 'http://anvil-53668:8500'\n\t\n\t"
user_config_overrides = "[Log]\nLevel = 'debug'\n"
test_secrets_overrides = ''
user_secrets_overrides = ''

[don.nodes.out]
[don.nodes.out.node]
url = '127.0.0.1:32997'
docker_internal_url = 'http://clnode-ac508:6688'

[don.nodes.out.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:32996/chainlink?sslmode=disable'
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@postgresql-aa692:5432/chainlink?sslmode=disable'

[[don.nodes]]
data_provider_url = 'http://localhost:8080/mock1'

[don.nodes.db]
user = 'chainlink'
password = 'thispasswordislongenough'
database = 'chainlink'
port = '5432'

[don.nodes.node]
image = 'public.ecr.aws/chainlink/chainlink'
tag = 'v2.17.0'
port = '6688'
test_config_overrides = "\n\t[[EVM]]\n\tChainID = '31337'\n\tMinIncomingConfirmations = 1\n\tMinContractPayment = '0.0001 link'\n\n\t\n\t[[EVM.Nodes]]\n\tName = 'default'\n\tWsUrl = 'ws://anvil-53668:8500'\n\tHttpUrl = 'http://anvil-53668:8500'\n\t\n\t"
user_config_overrides = "[Log]\nLevel = 'debug'\n"
test_secrets_overrides = ''
user_secrets_overrides = ''

[don.nodes.out]
[don.nodes.out.node]
url = '127.0.0.1:32999'
docker_internal_url = 'http://clnode-38394:6688'

[don.nodes.out.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:32998/chainlink?sslmode=disable'
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@postgresql-580eb:5432/chainlink?sslmode=disable'

[[don.nodes]]
data_provider_url = 'http://localhost:8080/mock1'

[don.nodes.db]
user = 'chainlink'
password = 'thispasswordislongenough'
database = 'chainlink'
port = '5432'

[don.nodes.node]
image = 'public.ecr.aws/chainlink/chainlink'
tag = 'v2.17.0'
port = '6688'
test_config_overrides = "\n\t[[EVM]]\n\tChainID = '31337'\n\tMinIncomingConfirmations = 1\n\tMinContractPayment = '0.0001 link'\n\n\t\n\t[[EVM.Nodes]]\n\tName = 'default'\n\tWsUrl = 'ws://anvil-53668:8500'\n\tHttpUrl = 'http://anvil-53668:8500'\n\t\n\t"
user_config_overrides = "[Log]\nLevel = 'debug'\n"
test_secrets_overrides = ''
user_secrets_overrides = ''

[don.nodes.out]
[don.nodes.out.node]
url = '127.0.0.1:33001'
docker_internal_url = 'http://clnode-bfc52:6688'

[don.nodes.out.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:33000/chainlink?sslmode=disable'
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@postgresql-ecb2c:5432/chainlink?sslmode=disable'

[don.out]
[[don.out.node]]
[don.out.node.node]
url = '127.0.0.1:32995'
docker_internal_url = 'http://clnode-cd9e2:6688'

[don.out.node.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:32994/chainlink?sslmode=disable'
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@postgresql-6d6d0:5432/chainlink?sslmode=disable'

[[don.out.node]]
[don.out.node.node]
url = '127.0.0.1:32997'
docker_internal_url = 'http://clnode-ac508:6688'

[don.out.node.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:32996/chainlink?sslmode=disable'
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@postgresql-aa692:5432/chainlink?sslmode=disable'

[[don.out.node]]
[don.out.node.node]
url = '127.0.0.1:32999'
docker_internal_url = 'http://clnode-38394:6688'

[don.out.node.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:32998/chainlink?sslmode=disable'
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@postgresql-580eb:5432/chainlink?sslmode=disable'

[[don.out.node]]
[don.out.node.node]
url = '127.0.0.1:33001'
docker_internal_url = 'http://clnode-bfc52:6688'

[don.out.node.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:33000/chainlink?sslmode=disable'
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@postgresql-ecb2c:5432/chainlink?sslmode=disable'
