name: Get Chainlink Image Tag
description: Gets the image tag and whether to publish the image based on the event type
# This gets the image tag and whether to publish the image based on the event type
# PR builds: pr-<pr_number>-<short_sha> (if label 'publish' is present publishes the image)
# develop builds: develop-<short_sha> and develop (only amd64)
# release builds: release-<short_sha>
# manual builds: <short_sha> (if publish is true publishes the image)

outputs:
  image-tag:
    description: The tag that will be used to build and push the Chainlink image
    value: ${{ steps.get-image-tag.outputs.image-tag }}

runs:
  using: composite
  steps:
      - name: Get image tag
        shell: bash
        id: get-image-tag
        run: |
          short_sha=$(git rev-parse --short HEAD)
          if [[ ${{ github.event_name }} == 'push' ]]; then
            if [[ ${{ github.ref_name }} == 'release/'* ]]; then
              echo "image-tag=release-${short_sha}" | tee -a $GITHUB_OUTPUT
            else
              echo "image-tag=develop" | tee -a $GITHUB_OUTPUT
            fi
          elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            echo "image-tag=${short_sha}" | tee -a $GITHUB_OUTPUT
          else
            if [[ ${{ github.event_name }} == "pull_request" ]]; then
              echo "image-tag=pr-${{ github.event.number }}-${short_sha}" | tee -a $GITHUB_OUTPUT
            fi
          fi
