[Network]
selected_networks = ["KROMA_SEPOLIA"]

[Soak.Common]
chainlink_node_funding = 1

[Soak.OCR2]
[Soak.OCR2.Common]
test_duration = "24h"

[Soak.OCR2.Soak]
time_between_rounds = "3m"

[OCR2.Common]
number_of_contracts = 2
