ChainID = '44787'
ChainType = 'celo'
FinalityTagEnabled = true
FinalityDepth = 2750 # mean finality time of ~37 minutes + 500 block buffer
LogPollInterval = '1s' # 1 sec block rate
NoNewHeadsThreshold = '1m'
NoNewFinalizedHeadsThreshold = '45m' # Set slightly higher than mean finality time

[GasEstimator]
EIP1559DynamicFees = true
PriceMin = '5 gwei' # Mean gas price around 5 gwei and celo txns are extremely cheap at ~0.00088 CELO per txn ($0.000058)
PriceMax = '1000 gwei' # DS&A recommendation
BumpMin = '2 gwei'

[GasEstimator.BlockHistory]
BlockHistorySize = 60

[HeadTracker]
HistoryDepth = 2750 # Same as FinalityDepth

[OCR]
ContractConfirmations = 1 # recommended for OP stack chains