ChainID = '4478'
ChainType = 'celo'
FinalityTagEnabled = true
FinalityDepth = 2750
LogPollInterval = '1s'
NoNewHeadsThreshold = '1m'
NoNewFinalizedHeadsThreshold = '45m'
OCR.ContractConfirmations = 1

[GasEstimator]
EIP1559DynamicFees = true
Mode = 'FeeHistory'

[GasEstimator.FeeHistory]
CacheTimeout = '4s'

[GasEstimator.BlockHistory]
BlockHistorySize = 60

[HeadTracker]
HistoryDepth = 2750