ChainID = "44787"
ChainType = "optimismBedrock"
FinalityTagEnabled = true
LogPollInterval = "1s"
NoNewHeadsThreshold = "40s"
MinIncomingConfirmations = 1
NoNewFinalizedHeadsThreshold = "15m"

[GasEstimator]
EIP1559DynamicFees = true
PriceMin = "1 wei"
PriceMax = "1000 gwei"
BumpMin = "100 wei"

[GasEstimator.BlockHistory]
BlockHistorySize = 60

[Transactions]
ResendAfterThreshold = "30s"

[HeadTracker]
HistoryDepth = 300

[NodePool]
SyncThreshold = 10

[OCR]
ContractConfirmations = 1