
[blockchain_a]

  [blockchain_a.out]
    chain_id = "43113"
    use_cache = true

    [[blockchain_a.out.nodes]]
      docker_internal_http_url = "https://ava-testnet.public.blastapi.io/ext/bc/C/rpc"
      docker_internal_ws_url = "wss://avalanche-fuji-c-chain-rpc.publicnode.com"
      http_url = "https://ava-testnet.public.blastapi.io/ext/bc/C/rpc"
      ws_url = "wss://avalanche-fuji-c-chain-rpc.publicnode.com"
