[contracts]

[blockchain_a]
type = "anvil"
image = "f4hrenh9it/foundry"
tag = "latest"

[data_provider]
port = 9111

[don]
nodes = 5

[don.node_spec]
data_provider_url = "http://host.docker.internal:9111"

[don.node_spec.node]
image = "public.ecr.aws/chainlink/chainlink"
tag = "v2.17.0"
user_config_overrides = """
"""