
[blockchain_a]
  chain_id = "31337"
  image = "f4hrenh9it/foundry:latest"
  port = "8545"
  type = "anvil"

[contracts]

[data_provider]
  port = 9111

[nodeset]
  nodes = 5
  override_mode = "all"

  [[nodeset.node_specs]]

    [nodeset.node_specs.db]
      image = "postgres:15.6"
      pull_image = true

    [nodeset.node_specs.node]
#      path to your binaries
#      capabilities = ["./ctf", "./ctf2"]
      image = "public.ecr.aws/chainlink/chainlink:v2.17.0"
      pull_image = true
