[[EVM]]
ChainID = "44787"
ChainType = "celo"
FinalityTagEnabled = true
FinalityDepth = 2500
LogPollInterval = "1s"
NoNewHeadsThreshold = "40s"
MinIncomingConfirmations = 1
NoNewFinalizedHeadsThreshold = "45m"

[EVM.GasEstimator]
EIP1559DynamicFees = true
PriceMin = "1 wei"
PriceMax = "1000 gwei"
BumpMin = "100 wei"

[EVM.GasEstimator.BlockHistory]
BlockHistorySize = 60

[EVM.Transactions]
ResendAfterThreshold = "30s"

[EVM.HeadTracker]
HistoryDepth = 300

[EVM.NodePool]
SyncThreshold = 10

[EVM.OCR]
ContractConfirmations = 1