name: CI Scripts

on:
  merge_group:
  pull_request:

jobs:
  changes:
    name: Find changed files
    runs-on: ubuntu-latest
    outputs:
      not_ignored_changes: ${{ steps.filter.outputs.every_changed == 'true' || steps.filter.outputs.any_changed == 'true' }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Filter other changes
        uses: ./.github/actions/filter-changes
        id: filter
        with:
          # Filter files that match **every** pattern in this list
          every-filter: |
            - '**'                     # Initially include all files
            - '!**/.github/**'         # Exclude all changes under the .github directory
          # Filter files that match **any** of these patterns
          any-filter: |
            - '.github/workflows/ci-scripts.yml'
            - '.github/actions/golangci-lint/**'
            - '.github/actions/setup-go/**'
            - '.github/actions/filter-changes/**'

  lint-scripts:
    # We don't directly merge dependabot PRs, so let's not waste the resources
    needs: changes
    if: ${{ (github.event_name == 'pull_request' ||  github.event_name == 'schedule') && github.actor != 'dependabot[bot]' && needs.changes.outputs.not_ignored_changes == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      # For golangci-lint-actions to annotate code in the PR.
      checks: write
      contents: read
      # For golangci-lint-action's `only-new-issues` option.
      pull-requests: read
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Golang Lint
        uses: ./.github/actions/golangci-lint
        with:
          id: scripts
          name: lint-scripts
          go-directory: core/scripts
          go-version-file: core/scripts/go.mod
          go-module-file: core/scripts/go.sum
          gc-basic-auth: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
          gc-host: ${{ secrets.GRAFANA_INTERNAL_HOST }}
          gc-org-id: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}

  test-scripts:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.not_ignored_changes == 'true' }}
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Setup Go
        uses: ./.github/actions/setup-go
        with:
          go-version-file: core/scripts/go.mod
          go-module-file: core/scripts/go.sum
      - name: Run Tests
        shell: bash
        working-directory: core/scripts
        run: go test ./...
