name: Find New Flaky Tests

on:
  workflow_dispatch:
    inputs:
      baseRef:
        required: true
        type: string
        description: 'The base reference or branch to compare changes for detecting flaky tests.'
        default: 'origin/develop'
      runCount:
        required: false
        type: string
        description: 'The number of times to run the tests to detect flaky tests.'
        default: '10'
      runThreshold:
        required: false
        type: string
        description: 'The threshold for the number of times a test can fail before being considered flaky.'
        default: '0.8'
      runWithRace:
        required: false
        type: boolean
        description: 'Run tests with -race flag.'
        default: true

jobs:
  trigger-flaky-test-detection:
    uses: ./.github/workflows/find-new-flaky-tests.yml
    with:
      baseRef: ${{ inputs.baseRef }}
      runCount: ${{ inputs.runCount }}
      runThreshold: ${{ inputs.runThreshold }}
      runWithRace: ${{ inputs.runWithRace }}